### ISSUE TITLE
When used in *ngFor, first item in list will be used for every instance

### ISSUE THREAD

**Issue by rinkstiekema** [arkon/ng-inline-svg#100]
When used in this format:

```
<li *ngFor="let item of items">
    <div [inlineSVG]="item.src"></div>
</li>
```

With items being the following array:
```
[
      {name: "google", img: 'assets/icons/google_icon.svg'},
      {name: "yahoo",  img: 'assets/icons/yahoo_icon.svg'},
      {name: "microsoft", img: 'assets/icons/outlook_blue.svg'}
]
```

For every item, the first svg in the array will be used for every item. Using the same `*ngFor`, but instead using an `<img>` tag works correctly.

**Comment by r0manchak** [comment]
Having the same issue across the whole page.

Every icon is replaced with the first one.

**Comment by arkon** [comment]
I can't actually seem to reproduce this. Can anyone make a minimal reproduction of it in StackBlitz or something?

**Comment by rinkstiekema** [comment]
https://angular-a7eqez.stackblitz.io

**Comment by arkon** [comment]
Ah, seems to be the same issue as #99.
