### ISSUE TITLE
Example for using setSVGAttributes

### ISSUE THREAD

**Issue by apawsey** [arkon/ng-inline-svg#105]
Thanks for the project!

For the life of me, I cannot figure out how to use setSVGAttributes... all I get is:
`Can't bind to 'setSVGAttributes' since it isn't a known property of 'div'`

Could you give any kind of example?

Thanks.

**Comment by arkon** [comment]
It hasn't been released yet. :)

**Comment by apawsey** [comment]
Ah... Well that's kinda mean! 😄  I didn't think to compare the package code with the code in the repository.
As I understand it,this would be the way to set the viewbox on the svg tag?

**Comment by apawsey** [comment]
Ok, I got the latest by installing straight from GitHub, and it works perfectly.

Just for others, syntax used:
`<div [inlineSVG]="...url" [setSVGAttributes]="{viewBox: '0 0 100 100' }">`
