### ISSUE TITLE
'undefined' is showing in IE11 when page is loading for few milliseconds

### ISSUE THREAD

**Issue by djay007** [arkon/ng-inline-svg#106]
Hi , 
I am facing strange issue in IE11. When intially page is loading that for few milliseconds its showing undefined instead of SVG icon. 

below is the console.log of handle event.

`<div aria-label="test" translate="" ng-reflect-translate="" ng-reflect-inline-s-v-g="assets/test.svg" ng-reflect-on-s-v-g-loaded="function (svg, parent) {
     ">undefined</div>`

**Comment by arkon** [comment]
Does this happen for any use of the directive in IE11 (i.e. no options, just an SVG)?
