### ISSUE TITLE
Evaluating Angular Logic

### ISSUE THREAD

**Issue by nj-coder** [arkon/ng-inline-svg#113]
Hi, 

I have an svg file which needs some angular logic like routerLink, click etc. Is there a way that we can make this work as for now even if i modify svg to include (click)="clicked()", the function simply does not trigger.

**Comment by arkon** [comment]
tl;dr That isn't supported, nor will it be.

You should instead have the handler as part of the parent, actually Angular-bound element (i.e. whatever you're using the directive on). If you need it to be based on clicking a part of the SVG itself, get references to its elements manually.
