### ISSUE TITLE
Support ID DOM conflict prevention

### ISSUE THREAD

**Issue by NiklasPor** [arkon/ng-inline-svg#114]
The svg injector should support the prevention of id conflicts. It is common usage of the module to include svgs from multiple sources. The usage of svgs from different sources creates the risk of colliding ids inside the svg elements.

For example [SVGInject](https://github.com/iconfu/svg-inject) makes all IDs inside the svg unique, before they are injected into the HTML.

I stumbled across this problem while using different svgs, which had a `clipPath` definition with the same id. The latter svg therefore wasn't displayed.

**Comment by arkon** [comment]
Kind of the same thing as #99.
