### ISSUE TITLE
Feature request: No baseURL option.

### ISSUE THREAD

**Issue by mikesimmonds** [arkon/ng-inline-svg#115]
In our project we are setting the base url in an interceptor and therefore I do not want to prepend the url with anything at all. 

The feature request: To add a way of not prepending the svg url with anything at all.

I have already implemented this locally be setting .forRoot({baseUrl: null}) and then checking this in the inline-svg>getAbsoluteUrl() method and simply returning the original url.  

I'm happy to submit a PR if you think this functionality would be valuable to others.

**Comment by arkon** [comment]
Yeah, feel free to submit a PR! Make sure to update the documentation too.

**Comment by mikesimmonds** [comment]
Great, I'll take a look over the next few days.

**Comment by emzet** [comment]
@arkon

Hi there, I do not think it is good approach, because with new release v9.1.0, our app does not work now. We set fake baseUrl option in InlineSVGModule and then in HttpInterceptor replace it with real one (which fetches ngx-config), but now svg requests never reach interceptor...

**Comment by emzet** [comment]
@arkon

**Comment by arkon** [comment]
@emzet For future reference, leaving comments on unrelated/closed issues isn't a good way to bring up issues.
