### ISSUE TITLE
Broken as of v8.6.0

### ISSUE THREAD

**Issue by RGunning** [arkon/ng-inline-svg#118]
change to tsconfig  is breaking imports

``` 
Details:

   node_modules/ng-inline-svg/lib/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){export { InlineSVGConfig } from './inline-svg.config';
                                                                                             ^^^^^^

    SyntaxError: Unexpected token export
```

**Comment by arkon** [comment]
Reverted in v8.6.1.

**Comment by remigasas** [comment]
I cannot find version 8.6.1 latest seems to be 8.6.0
https://www.npmjs.com/package/ng-inline-svg?activeTab=versions

**Comment by arkon** [comment]
Indeed. I meant 9.0.1.

**Comment by remigasas** [comment]
I think 9.* versions are for angular8 and 8.* for angular7.
There are no significant functionality changes between 8.6.0 and 8.5.1, but devs (like us) that still uses angular7 gets into problem when using latest version with angular7. 
Could 8.6.2 be released with a fix ?

**Comment by remigasas** [comment]
Opened a PR at https://github.com/arkon/ng-inline-svg/pull/126
