### ISSUE TITLE
Error Inline SVG

### ISSUE THREAD

**Issue by agyrafa** [arkon/ng-inline-svg#12]
Im get this error after import the package

`GET http://localhost:3000/ng2-inline-svg 404 (Not Found)`

In my app.module, I enter this 
`import { InlineSVGModule }    from 'ng2-inline-svg';`
and then 
`@NgModule({
  	imports: [ InlineSVGModule ]`

**Comment by agyrafa** [comment]
okay, I managed to work, but now Im trying to add this to my code: 
`<div class="my-icon" [inlineSVG]="'/public/assets/media/img/{{service.image}}.svg'"></div>`

and Im getting this error on my console:
![screen shot 2016-11-07 at 11 49 41](https://cloud.githubusercontent.com/assets/10052533/20060056/74c8e7ea-a4e0-11e6-9284-5e3994bf7ef7.png)

**Comment by arkon** [comment]
Try:

``` html
<div class="my-icon" inlineSVG="'/public/assets/media/img/{{service.image}}.svg'"></div>
```

Or if you have some variable `svgPath` in the script that holds the value of `'/public/assets/media/img/{{service.image}}.svg'`:

``` html
<div class="my-icon" inlineSVG="svgPath"></div>
```

**Comment by agyrafa** [comment]
It worked! Thanks ;)
