### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by pararell** [arkon/ng-inline-svg#120]
`[x ] bug report`

I tried to use svg.config.ts with clientOnly option as true, but still has problem with serverRendering 
- Angular v. 8.2.6
- Typescript v. 3.5.3

- Problem is with this line - `__metadata("design:type", Element) ` 

- `ReferenceError: Element is not defined` is result when I build server-rendering app

**Comment by catalinroncea** [comment]
I have the same error "Element is not defined" when building my app with app shell like:
ng run my-app:app-shell:production

**Comment by herreraLeonar** [comment]
I have the same problem when execute: npm run dev:ssr

Somebody find how fix?

**Comment by mustafakunwa** [comment]
Is there any fix for this yet, Getting the same issue
