### ISSUE TITLE
Can't import latest versions ng-inline-svg - only with version 9.2.X 

### ISSUE THREAD

**Issue by JulienLeal** [arkon/ng-inline-svg#129]
I'm trying to use your module, but I getting this error:

ERROR in src/app/app.module.ts:3:33 - error TS2307: Cannot find module 'ng-inline-svg'. 3 import { InlineSVGModule } from 'ng-inline-svg';

Well, obviously, I had been installed the module correctly.
Versions 9.2.0 and 9.2.1 have this error for me, but with the version 9.0.0 works.

**Comment by arkon** [comment]
Try 9.2.2? I screwed up what was included in the published artifacts in 9.2.1, so I've unpublished that.

**Comment by JulienLeal** [comment]
Ther version 9.2.2 is ok. Thanks
