### ISSUE TITLE
Class not detected from node modules

### ISSUE THREAD

**Issue by Ramees-Raja** [arkon/ng-inline-svg#130]
T am working in angular 8 with this 'ng-inline-svg' package , My project was working fine, But today I reinstall all my npm packages in this project, now I displaying  **Error ERROR in src/app/app.module.ts(14,33): error TS2307: Cannot find module 'ng-inline-svg'.** when i serve the project, but the folder **ng-inline-svg** already existing in my node modules.

When I replace the node modules folder with my old backup node modules folder, There is no problem, I think this is an update related issue

hope you will fix it soon, Thank you....

**Refferances**
1. **error Message in bash when trying o serve project**
![image](https://user-images.githubusercontent.com/20684864/72237612-1990ab00-3601-11ea-9e93-7bccd26c38cc.png)

2. **Error in vs code**
![image](https://user-images.githubusercontent.com/20684864/72237712-72604380-3601-11ea-9c57-136a05c63269.png)

3. **In node modules**
![image](https://user-images.githubusercontent.com/20684864/72237742-90c63f00-3601-11ea-9985-b07204dea62d.png)

**Comment by arkon** [comment]
Do you have v9.2.1 installed somehow? If so, install v9.2.2.

**Comment by AndrewLTaft** [comment]
It appears to be related to v8.6.2.  I changed our package version to 8.6.1 and no longer see the issue.  On npm the number of files in 8.6.2 dropped from 35 to 11.  I think there was an issue with the packaging.

**Comment by arkon** [comment]
You're right, I messed up that release. I'll need to fix that tonight.

**Comment by arkon** [comment]
Published v8.6.3.
