### ISSUE TITLE
Support for Angular 9

### ISSUE THREAD

**Issue by scottpetrovic** [arkon/ng-inline-svg#132]
I know Angular 9 is really new, but was just seeing if there were plans to support it. I just did a test trying to upgrade one of my projects and it looks like they changed things a bit with the forRoot() property. This library is having a rough time with the upgrade. It looks like it is related to this.

https://angular.io/guide/deprecations#modulewithproviders-type-without-a-generic

**Comment by arkon** [comment]
I probably won't get around to looking at this anytime soon since I don't actually use Angular for anything anymore. I'd be willing to review/accept PRs though, if anybody else wants to work on it...

**Comment by scottpetrovic** [comment]
Alright. I tried playing around with it a bit but was failing trying to get it to work in Angular 9. Angular 9 is starting to use this new "differential loading" concept with a new compiler, so some of the setup and configuration options changed and making it more difficult to actually build.

**Comment by arkon** [comment]
Anyway, I actually did end up getting around to looking at this.

Released as v10.0.0, which seems to work fine in my basic demo env at least.

**Comment by scottpetrovic** [comment]
Wow that is great. Thank you so much for working on this still.

**Comment by scottpetrovic** [comment]
I tried updating my package and it is having issues. It seems like it might be some bug in Angular though that the team is working out. With your new 10.0 version, my project compiles fine, but my terminal throws an error when trying to do an "ng serve":

```
ERROR in node_modules/ng-inline-svg/lib_commonjs/inline-svg.module.d.ts:3:22 - error NG6002: Appears in the NgModule.imports of AppModule, but could not be resolved to an NgModule class

3 export declare class InlineSVGModule {
```

This seems to be one of the github ticket for the Angular team trying to resolve it. It seems related to the new Ivy renderer.
https://github.com/angular/angular/issues/35255

**Comment by arkon** [comment]
I'll keep an eye on it, but I'll probably just wait for the Angular team to keep ironing out all these Ivy bugs.

I assume they don't expect every library to be updated every time they release an update.....
