### ISSUE TITLE
Caching svg symbol

### ISSUE THREAD

**Issue by proambb** [arkon/ng-inline-svg#133]
Hi! It looks like caching of svg symbols does not work. I use the following code
```html
<div class="uwf-svg-icon"
     [onSVGLoaded]="onSvgLoaded"
     [cacheSVG]="true"
     [inlineSVG]="'/assets/images/icons-sprite/svg-symbols.svg#' + icon"></div>
```
My expectation is that it will first cache sprite file `/assets/images/icons-sprite/svg-symbols.svg` and then take svg from it, but instead it does request for each different `icon` value. 

Is it possible to configure component in such a way to load sprite file only once?

**Comment by proambb** [comment]
@arkon I don't know how good is this solution, but I forked project and change [this line](https://github.com/arkon/ng-inline-svg/blob/master/src/svg-cache.service.ts#L40) 
to this 
```js
const svgUrl = (resolveSVGUrl
            ? this.getAbsoluteUrl(url)
            : url).replace(/#.+$/, '');
```

Please let me know your opinion. If it is ok, I'll create a PR. 

So far it works well in our project and sprite file requested only once

**Comment by arkon** [comment]
A PR would be great!
