### ISSUE TITLE
Trigger onchanges when attributes are changed

### ISSUE THREAD

**Issue by iggybotes** [arkon/ng-inline-svg#134]
More of a feature request but are you able to trigger ` this._insertSVG();` when input: `setSVGAttributes` is changed? This will allow people to dynamically change the width and height of the icon (and possibly other attributes).

```
if (changes['inlineSVG'] || changes['setSVGAttributes']) {
      this._insertSVG();
    }
```

**Comment by qubiack** [comment]
This was closed without any conclusion?

**Comment by arkon** [comment]
It was fixed 4 months ago, which is the referenced commit.

**Comment by qubiack** [comment]
@arkon sorry - my fault. Thanks for the quick response guy! Great job.
