### ISSUE TITLE
Issue when updating angular to version 9 and Ivy: ERROR in Symbol InlineSVGModule

### ISSUE THREAD

**Issue by balteo** [arkon/ng-inline-svg#139]
Hello,

I am using **ng-inline-svg** (latest version i.e. 10.0.0) and I am trying to migrate a library to **angular 9 with Ivy**. Since updating the angular version, I get the following error:

    ERROR in Symbol InlineSVGModule declared in C:/git/XXX/node_modules/ng-inline-svg/lib_commonjs/inline-svg.module.d.ts is not exported from ng-inline-svg (import into C:/git/XXX/src/app/app.module.ts)

I have imported the inline svg module as follows in `app.module.ts`:

    InlineSVGModule.forRoot(),

Can someone please help?

**Comment by arkon** [comment]
Did you check if the file's there? Did you try reinstalling the dependency?

**Comment by melodysummer** [comment]
angular 10 has the same problem. It seems not compatible with the latest ng version
could you fix it?

**Comment by arkon** [comment]
v11.0.0 was released in late July, which _should_ work with Angular 10.
