### ISSUE TITLE
Why it doesn't change css style?

### ISSUE THREAD

**Issue by junjunruan** [arkon/ng-inline-svg#14]
I am using angular version 2.1.2 and this package, but it can't change css style for svg.
Can you help take a look it? 

Below is my code:

inside template of app.component.ts:
```
<div class="app-div">App</div>
<div class="demo-svg1" aria-label="My icon 1" [inlineSVG]="'./image.svg'"></div>
```

In css of app.component.ts:
```
.app-div {
  color: red;
}

svg {
    fill: currentColor;
}

.demo-svg1 {
    color: orangered;
}
```

Here is the code in plunker: http://plnkr.co/edit/971LgsZTzqUq5vEY9cdF?p=preview. (just focus on code in component and css, as I can't include ng2-inline-svg package correctly on plunker)

**Comment by arkon** [comment]
Is the SVG file in the Plunker the exact one that you're also trying to use?

**Comment by junjunruan** [comment]
Yes, it is. I copied from your github demo project.

**Comment by arkon** [comment]
Can you try inspecting the element? You should be able to see what styles are being inherited by the `path`/`circle` inside the injected SVG element.

**Comment by junjunruan** [comment]
When I inspect the element, the styles is inherited by path/circle, it just didn't work.
If I add "fill: red" inside `element.style {}`, it works.

Here is the screenshot:
![alt text](http://i.imgur.com/wqujWjB.png)

BTW, in your github README page, you didn't mention about what should we put in system.config.js file. Here is part of my config code, just to make sure it is correct.

```
paths: {
      'npm:': 'node_modules/'
    },
map: {
   'ng2-inline-svg': 'npm:ng2-inline-svg/lib'
},
packages: {
      'ng2-inline-svg': {
          main: './index.js',
          defaultExtension: 'js'
      }
}
```

And the code I put in app.module.ts file is exactly the same as you did.
Did you see anything wrong with my code?

**Comment by arkon** [comment]
Your SystemJS config is fine if it's injecting the SVG.

The styles you were attempting to do don't work because of [View Encapsulation](https://angular.io/docs/ts/latest/guide/component-styles.html#!#view-encapsulation), similar to #9.

(Feel free to reopen if you still can't figure it out)

**Comment by junjunruan** [comment]
@arkon - Thanks for the reference. However, I still have no idea about how to solve my problem. Can you show how should I change my code based on the plunker example?

**Comment by arkon** [comment]
@junjunruan Try actually putting the styles in the component decorator (as `styles` rather than as a link in `styleUrls`).

**Comment by junjunruan** [comment]
@arkon Thanks for your quick response. I have to use styleUrls as there are many styles need to be put, it's more clear to put it in styleUrls. 

Based on the suggestion from the guy who posted #9,  I solved it by using the following styles in my external css file:
```
.app-div {
    color: green;
}

:host /deep/  svg {
    fill: currentColor;
}

.demo-svg1 {
    color: orangered;
}

```

**Here is another topic:**

Actually the reason I use this package is to allow me `dynamically` change `part` of the color inside svg (like the color of path or circle by clicking a button on html). I am not sure if your package can help me do that as I didn't get enough information from your github page or even demo. Can you show me how to do that in my plunker example?

I tried remove class based on you demo example with code 
```<div class="demo-svg1" aria-label="My icon 1" [inlineSVG]="'app/image.svg'" [removeSVGAttributes]="['fill']"></div>```. However, it doesn't work for me.

**Comment by arkon** [comment]
There are a lot of resources out there on learning how to animate SVGs:
- https://css-tricks.com/animating-svg-css/
- http://stackoverflow.com/questions/14756422/animate-svg-path-fill-using-css
- https://css-tricks.com/guide-svg-animations-smil/

Some of these rely on CSS, some rely on regular old SVG features. Either way, all this package does is allow you to easily inline the SVG into the DOM so that it's possible to style it directly via CSS as you normally would with other DOM elements (so long as you target the correct elements with the correct selectors).

**Comment by junjunruan** [comment]
Thanks @arkon. I found that I can use ```[ngClass]="setClasses()"``` to change the style of svg. 

Your package is very useful, but I am also concern about security issue while using it. Will it have issue like this: https://github.com/angular/angular/issues/9277

**Comment by arkon** [comment]
@junjunruan What you linked isn't really a _security_ issue, but this package won't be affected by it. It's directly inserting the SVG file into the DOM, and it won't go through Angular's parser.

**Comment by junjunruan** [comment]
@arkon - Great! I appreciate all your help.

**Comment by joshualeduc** [comment]
It looks like /deep/ is being deprecated. I'm currently using ::ng-deep right now, but is there another way to get around the issue? 

https://angular.io/guide/component-styles#deprecated-deep--and-ng-deep

**Comment by arkon** [comment]
@joshualeduc Frankly, it seems like a massive design flaw with Angular in general, but I haven't really found a nice solution to it. I'm not sure if the Angular team is really thinking about this problem though.
