### ISSUE TITLE
Display by link

### ISSUE THREAD

**Issue by taxioma** [arkon/ng-inline-svg#146]
Hi!
I want to display my svg scheme by link, but have a trouble.
I have link and I find how to set baseUrl in docs, but in code it doesn`t work/
When I try 
```
 constructor(
    svgService: SVGCacheService
  ) {
svgService.setBaseUrl({ baseUrl: 'https://mysite.com/myapp/' });
```

i have `Expected 0 arguments, but got 1.`

Help me, pls...

**Comment by arkon** [comment]
`setBaseUrl` isn't meant to be called like that, as the type error suggests.

You should ideally just be configuring it for the root module, i.e.

```js
InlineSVGModule.forRoot({ baseUrl: 'https://mysite.com/myapp/' })
```
