### ISSUE TITLE
Exception when fetching fails

### ISSUE THREAD

**Issue by JohnKis** [arkon/ng-inline-svg#149]
In rare cases when the HTTP request fetching the SVG fails, the following exception is thrown:
```
ERROR TypeError: Cannot read property 'charAt' of null
```

I did some digging an it's due to the finalize operator here: https://github.com/arkon/ng-inline-svg/blob/master/src/svg-cache.service.ts#L62

What seems to happen is that the flow continues even when the request failed and as a result an exception is being thrown from the isUrlSymbol method here: https://github.com/arkon/ng-inline-svg/blob/master/src/svg-util.ts#L9

It'd be great to have a way to suppress this exception and pipe the HTTP error to the `onSVGFailed` output instead.

**Comment by arkon** [comment]
A PR to fix this would be welcomed!

**Comment by JohnKis** [comment]
Sorry, didn't realise I already opened an issue for this.

When I'll have some free time, I'll look into creating a PR for this.
