### ISSUE TITLE
Add inline SVG dynamically

### ISSUE THREAD

**Issue by ishanuda** [arkon/ng-inline-svg#151]
Hi,
Inline SVG is a great library to be used and thank you very much for all the contributors.

I would like to know whether the library can be used to add SVGs dynamically to the component.

For example, I am loading an external web page with the help of an iFrame.

This HTML page is having references to SVG images with IMG(s).

I would like to replace these IMG elements with the help of inline-svg dynamically.

A dynamic directive example is explained by Jagadesh in the following link for an example:

[How to add directive dynamically in angular 2/4/6?](https://upliftskills.us/blog/2018/11/08/how-to-add-directive-dynamically-in-angular-2-4-6/)

Regards.
Shan

**Comment by arkon** [comment]
There's no built-in support for something like this, no.

**Comment by ishanuda** [comment]
Hi, Thank you very much for the comment.

Any idea of adding this kind of feature in future releases?

Regards

**Comment by arkon** [comment]
I don't plan to, no. If you'd like to add it, please open a PR.

**Comment by ishanuda** [comment]
Thank you very much
