### ISSUE TITLE
IE11 embedded styles bug

### ISSUE THREAD

**Issue by Kosmonaft** [arkon/ng-inline-svg#17]
Hey,

In IE11 if the styles of the svg are embedded into the svg file, it's not adding applying them into the svg.
This definitely is not a problem of the plugin but it's going to be amazing if you can add a fix for it.

So for example the icon
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 45 50"><defs><style>.cls-1-big{fill:#d4edff;}.cls-2-big,.cls-3-big{fill:#0073cf;}.cls-3-big{opacity:0.5;}.cls-4-big{fill:none;stroke:#0073cf;stroke-linecap:round;stroke-linejoin:round;stroke-width:2px;}</style></defs><title>Registration_3</title><g id="Layer_2" data-name="Layer 2"><g id="Layer_1-2" data-name="Layer 1"><g id="Help"><g id="Form"><rect class="cls-1-big" x="1.5" y="1.5" width="42" height="47" rx="8.5" ry="8.5"/><path class="cls-2-big" d="M35,3a7,7,0,0,1,7,7V40a7,7,0,0,1-7,7H10a7,7,0,0,1-7-7V10a7,7,0,0,1,7-7H35m0-3H10A10,10,0,0,0,0,10V40A10,10,0,0,0,10,50H35A10,10,0,0,0,45,40V10A10,10,0,0,0,35,0Z"/><rect class="cls-3-big" x="9" y="11" width="7" height="7" rx="1.5" ry="1.5"/><line class="cls-4-big" x1="21" y1="15" x2="35" y2="15"/><rect class="cls-3-big" x="9" y="21" width="7" height="7" rx="1.5" ry="1.5"/><line class="cls-4-big" x1="21" y1="25" x2="35" y2="25"/><rect class="cls-3-big" x="9" y="31" width="7" height="7" rx="1.5" ry="1.5"/><line class="cls-4-big" x1="21" y1="35" x2="35" y2="35"/></g></g></g></g></svg>`

 it's looking like this in IE 11

![image](https://cloud.githubusercontent.com/assets/851709/21039283/ea2b1724-be30-11e6-8239-b8272b09e28b.png)

I think the fix for it can be the following code:
```
var styleTags = svg.querySelectorAll('style');
      forEach.call(styleTags, function (styleTag) {
        styleTag.textContent += '';
      });
```

Regards

**Comment by arkon** [comment]
I'm assuming it looks like that in every browser and not just IE11?

**Comment by Kosmonaft** [comment]
In Chrome, Firefox and Safari it's looking good

**Comment by arkon** [comment]
I see this was an issue here too: https://github.com/iconic/SVGInjector/issues/23

I'll add the option.

**Comment by arkon** [comment]
Added a `forceEvalStyles` option in v1.4.0.

**Comment by arkon** [comment]
(I read the original post incorrectly...)
