### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by tulitheprogrammer** [arkon/ng-inline-svg#19]
ctorParameters.map is not a function to ctorParameters.map is not a function

  "@angular/core": "2.1.0",

**Comment by arkon** [comment]
Could you try updating to a newer version of Angular?

**Comment by tulitheprogrammer** [comment]
I wish, 
It's a very large project.
Is any workaround for this issue ?

**Comment by arkon** [comment]
You could try installing `ng2-inline-svg@1.4.0`, since that used an older version of the compiler.

As a side note, I'll probably need to up the minimum version of Angular for this library...

**Comment by tulitheprogrammer** [comment]
Great option!
I'll try this. 
BTW I've tried updating the angular version earlier,
 which lead to a new problem on "angular universal"

**Comment by arkon** [comment]
Unfortunately, I haven't had any experience with that. You can probably find stuff on Google though, tons of other people have had issues when updating Angular.

**Comment by tulitheprogrammer** [comment]
Regarding your recommendation, it nows works great.
I just had to fix  the problem on FF with 
<base href="/"> 
(replaced it with APP_BASE_HREF declaration on app main module).
in order to work with SVG sprites (in-page anchors issue).

10x for everything :)

**Comment by arkon** [comment]
Awesome! If you do ever update to Angular >=2.3.0, be sure to switch over from `ng2-inline-svg` to `ng-inline-svg`, since I renamed it. :)
