### ISSUE TITLE
IE10 support?

### ISSUE THREAD

**Issue by Xample** [arkon/ng-inline-svg#20]
Would it require a shim like this: https://github.com/dnozay/innersvg-polyfill ?
The problem I faced is replacing the content in place was not working while adding an SVG into the current element was fine.

Here below my own directive (inspired by http://stackoverflow.com/a/38600444/532695 ):
```ts
import {Directive, Input, ElementRef, OnChanges, SimpleChange} from '@angular/core';
import {Http} from '@angular/http';

interface Inputs<T> {
  useLoader:T;
}

interface Changes<T> extends Inputs <T> {
  [propertyName:string]:T;
}

/**
 * This directive adds an SVG element into the host element.
 * The content of the SVG will be a symbol specified through the input parameter (url + fragment).
 * This is aimed to allow IE to use the "<svg><use>" feature.
 */
@Directive({
  selector: '[ic-svg-use]'
})
export class UseLoaderDirective implements Inputs<string>, OnChanges {

  @Input('ic-svg-use') public useLoader:string;

  constructor(private element:ElementRef,
              private http:Http) {
  }

  public ngOnChanges(changes:Changes<SimpleChange>):void {
    if (changes.useLoader.currentValue !== undefined) {
      this.sourceChanged();
    }
  }

  private sourceChanged():void {
    const [src, name]:string[] = this.useLoader.split('#');
    if (this.isSourceValid(src, name)) {
      this.loadSVG(src, name);
    }
  }

  private isSourceValid(src:string, name:string):boolean {
    return (src !== undefined) && (name !== undefined);
  }

  private loadSVG(src:string, name:string):void {

    this.http.get(src)
      .map(res => res.text())
      .map(svg => this.convertToSVG(svg, name))
      .toPromise()
      .then(svg => this.applySVG(svg))
      .catch(err => console.log(err));
  }

  private applySVG(content:string):void {
    if (this.isHostElementSVG()) {
      this.replaceSVGContent(content);
    } else {
      this.embedSVG(content);
    }
  }

  private replaceSVGContent(content:string):void {
    // This will fail on IE10 if no shim https://github.com/dnozay/innersvg-polyfill
    const nativeElement:HTMLElement = this.element.nativeElement;
    nativeElement.setAttribute('viewBox', this.extractViewBoxAttribute(content));
    nativeElement.innerHTML = this.extractTagContent(content);
  }

  private embedSVG(content:string):void {
    this.element.nativeElement.innerHTML = content;
  }

  private isHostElementSVG():boolean {
    const nativeElement:HTMLElement = this.element.nativeElement;
    return nativeElement.tagName.toLowerCase() === 'svg';
  }

  private convertToSVG(svg:string, name:string):string {
    const symbolOuterHTML:string = this.extractSymbol(svg, name);
    return this.replaceSymbolWithSVG(symbolOuterHTML);
  }

  private extractTagContent(svg:string):string {
    const endOfOpeningTag:number = svg.indexOf('>');
    const startOfClosingTag:number = svg.lastIndexOf('</');
    return svg.substring(endOfOpeningTag + 1, startOfClosingTag);
  }

  private extractViewBoxAttribute(svg:string):string {
    const viewBoxComplete:string = svg.match(/viewBox=("|').*("|')/i)[0] || '';
    const viewBoxValue:string = viewBoxComplete.substring(9, viewBoxComplete.length - 1);
    return viewBoxValue;
  }

  private extractSymbol(svg:string, name:string):string {
    const matchSymbolWithId:string = `<symbol(.*?)id=("|')${name}("|')(.*?)>([\\S\\s]*?)<\/symbol>`;
    const result:string[] = svg.match(new RegExp(matchSymbolWithId, 'gim')) || [];
    return result[0];
  }

  private replaceSymbolWithSVG(symbolOuterHTML:string):string {
    return symbolOuterHTML.replace('<symbol', '<svg').replace('</symbol>', '</svg>');
  }
}
```

**Comment by arkon** [comment]
I didn't actually know that was an issue! 😅 

Are you saying that you tried this library in IE10 but it only works if you've set it to append the SVG?

**Comment by Xample** [comment]
I simply tried using www.browserstack.com on IE10, and no image.
The issue I know on IE10 is setting innerHTML with SVG content will not work, reason why there is a shim for it. I however did not try to use the shim with your library.

By experience appending an html element will work, replacing the current one will not by default.

**Comment by arkon** [comment]
Thanks for the heads up!

**Comment by Xample** [comment]
Your demo seems to work well  on IE10. (My own test using the url fragments (sprite.svg#symbol) was not working properly) I should try again to make sure of the problem.

![image](https://cloud.githubusercontent.com/assets/944605/22398650/656baa92-e5a6-11e6-81ff-97193ff11479.png)

**Comment by Xample** [comment]
The other option I had to support SVG on IE10 + IE11 was:
https://github.com/jonathantneal/svg4everybody
But it relies on "Window.requestAnimationFrame()" to check for svg source changes and I feel like this slows down the whole rendering. Not very ng2 to summarize.

**Comment by arkon** [comment]
That last one is supposed to be showing a regular image as a fallback for a non existent SVG, so it seems like that's failing. I'll try to take a look at some point too.

**Comment by Xample** [comment]
![image](https://cloud.githubusercontent.com/assets/944605/22422535/60004110-e706-11e6-9040-47169debfe57.png)

Another screenshot for inline svg. Chrome on the left, IE11 on the right

using:
```html
<div class="my-icon" aria-label="My icon" [inlineSVG]="'/assets/sprite.svg#password'"></div>
```

**Comment by arkon** [comment]
What's the SVG like?

**Comment by ertkjern** [comment]
Might be the use tag which is not supported in IE10
https://developer.mozilla.org/en-US/docs/Web/SVG/Element/use

**Comment by arkon** [comment]
Oddly, that fish icon is using the `use` tag to be displayed. The failing one in the demo is the fallback image... 🤔

**Comment by hccampos** [comment]
Seems like this might be related to https://github.com/arkon/ng-inline-svg/blob/5329b820c869229e4a8a2b81f66fe97816138b4b/src/inline-svg.directive.ts#L144

We are getting this error when replacing icons in IE11. Here is a related SO question: http://stackoverflow.com/questions/18919560/object-doesnt-support-property-or-method-remove

EDIT: Just created a PR for it https://github.com/arkon/ng-inline-svg/pull/33
