### ISSUE TITLE
Not respecting base-href and trying to access subdirectory, img not found

### ISSUE THREAD

**Issue by joshuaohana** [arkon/ng-inline-svg#21]
Love the library, works great; however...

Under normal operation, like loading localhost/page1, localhost/page2, everything works great.

If I nav to localhost/page1/sectionA from within the app of course the img is still there, but if I do a hard reload then the lib tries to load the image from localhost/page1/img/ instead of localhost/img like it normally does.

How can we resolve so it does not do this?

Looking through your source I see the following, which if you hard reload onto localhost/page1/sectionA the base.href will come back as localhost/page1, when we want it to resolve to just localhost

`const base = this._document.createElement('BASE') as HTMLBaseElement;`

*fixed*
Turns out all I had to do was add a leading forward slash in the invlineSvg path

**Comment by arkon** [comment]
Glad you got it working!

**Comment by stieler-it** [comment]
I think the leading slash will only work if your application is running in the root of your domain.

**Comment by arkon** [comment]
It'll work if the image is located there. Absolute paths will always work, but relative paths may have issues due to routing, of course.
