### ISSUE TITLE
Use renderer service for element interaction

### ISSUE THREAD

**Issue by artaommahe** [arkon/ng-inline-svg#22]
Currently `_insertEl()` method use direct DOM property changing/methods call.
https://github.com/arkon/ng-inline-svg/blob/master/src/inline-svg.directive.ts#L152
It's bad if app is running in service worker or on server. Would be cool to use [`Renderer`](https://angular.io/docs/ts/latest/api/core/index/Renderer-class.html) service here for same things.

**Comment by arkon** [comment]
Quite frankly, this library assumes there's direct access to the DOM since you're trying to add something to it anyway. The Renderer service seems lacking (e.g. roundabout ways of setting `innerHTML`, no obvious way to insert a node before another, etc.), but if you know how to use it nicely, I'd welcome a PR.

**Comment by intellix** [comment]
Another thing: View encapsulation.
I want to style individual pieces of the inlined SVG within a component and they don't have the view encapsulated DOM properties added

The inserted SVG doesn't have `_ngcontent-c12` etc added

**Comment by arkon** [comment]
I switched to using [Renderer2](https://angular.io/docs/ts/latest/api/core/index/Renderer2-class.html#!#setValue-anchor) now that Angular 4 is out. Of course, that means you'll need at least Angular 4 for this now. For reference, this is [the DOM implementation](https://github.com/angular/angular/blob/92084f2b6a7cc1c81e31b8f413424223e62806d8/packages/platform-browser/src/dom/dom_renderer.ts#L99) of it.

I'll be publishing a new major version to NPM with the change soon. I'll need to look into the view encapsulation a bit though, although I don't think I'll be doing that, @intellix. After all, it's not a new component.
