### ISSUE TITLE
how to add some class in the inline svg?

### ISSUE THREAD

**Issue by wfsovereign** [arkon/ng-inline-svg#23]
Hi, 

  I find the inputs of options don't have a way to modify style or class of insert svg node. this is intentional or ?

**Comment by arkon** [comment]
This is purely meant for inserting the SVG directly into the DOM. If the original SVG has styles or classes already, then that's great, but otherwise, you'll need to edit the original SVG.

**Comment by wfsovereign** [comment]
I think the sense purely is very nice, but, I think if we have a interface to modify it is better. because svg element is very flexible at website, we can do more thing by the dynamic styles.

**Comment by arkon** [comment]
Sorry, that seems beyond the scope of what this directive is meant for. You can try using your own function to mutate the SVG using the `onSVGInserted` output callback.
