### ISSUE TITLE
View encapsulation

### ISSUE THREAD

**Issue by arkon** [arkon/ng-inline-svg#24]
As mentioned in #22, view encapsulation might be nice to have.

> I want to style individual pieces of the inlined SVG within a component and they don't have the view encapsulated DOM properties added
> The inserted SVG doesn't have _ngcontent-c12 etc added

An [embedded view](https://angular.io/docs/ts/latest/api/core/index/ViewContainerRef-class.html#!#createEmbeddedView-anchor) might be useful for this.

**Comment by intellix** [comment]
Just to illustrate why I think this issue has value :) 

Currently I'm using ViewEncapsulation throughout my application but inlineSVG rendered elements don't receive the required properties: `_ngcontent-c12` etc. 

If I need to style individual pieces of an SVG, I have to set `ViewEncapsulation.None` for my component and hack it back in with CSS:

### Without ViewEncapsulation

```ts
@Component({
  encapsulation: ViewEncapsulation.None,
  selector: 'xc-header',
  template: '<i class="icon-burger" inlineSVG="burger.svg"></i>',
  styles: [`
    xc-header {
      background: #f8f8f8;

      .icon-burger {
        path {
          &:nth-child(1) { fill: red }
          &:nth-child(2) { fill: green }
          &:nth-child(3) { fill: blue }
        }
      }
    }
  `],
})
export class HeaderComponent { }
```

### With ViewEncapsulation

```ts
@Component({
  selector: 'xc-header',
  template: '<i class="icon-burger" inlineSVG="burger.svg"></i>',
  styles: [`
    :host {
      background: #f8f8f8;
    }

    .icon-burger {
      path {
        &:nth-child(1) { fill: red }
        &:nth-child(2) { fill: green }
        &:nth-child(3) { fill: blue }
      }
    }
  `],
})
export class HeaderComponent { }
```

**Comment by intellix** [comment]
Also, a realisation just now is that without ViewEncapsulation, you can't have multiple of something on the same page as the styles applied are globally applied to each of them :(

Was trying to pass in a theme input to my component containing inlineSVG items, but it'll affect all of them on the page.

Workaround I suppose:

```
<xc-burger [dark]="true"></xc-burger>
```

```
@HostBinding('class.dark') @Input() dark = false;
```

```
xc-burger.dark {
  
}
```

**Comment by arkon** [comment]
@intellix Is `xc-burger` a component containing an SVG?

I still have to find the time to look more into this and figure out how to do it. I _think_ an Embedded View is what I want, but it seems somewhat complicated. :\

**Comment by intellix** [comment]
Aye, just like the example above, except this time I added the ability to change the theme as well :)

**Comment by christarczon** [comment]
You can use /deep/ for this if you're using emulated encapsulation.

    .icon-burger {
      /deep/ path {
        &:nth-child(1) { fill: red }
        &:nth-child(2) { fill: green }
        &:nth-child(3) { fill: blue }
      }
    }

**Comment by intellix** [comment]
Aye, but all that does is adds a global style to the body like: 

```css
.icon-burger path:nth-child(1) { fill: red }
```

**Comment by christarczon** [comment]
No, it leaves the encapsulation attribute off everything after /deep/. (at least for emulated, /deep/ doesn't work with Shadow DOM)

I use it in a nav strip to set the default color for each icon and this is the rule in it generates for me:
`nav[_ngcontent-c1] a[_ngcontent-c1] svg {`

Then for my active one:
`nav[_ngcontent-c1] .active[_ngcontent-c1] use {`

**Comment by arkon** [comment]
I think the use of `/deep/` makes sense to me, but if for whatever reason having the SVG wrapped by an extra component is useful to you, that's been added in v3.4.0.

**Comment by kenisteward** [comment]
is the inserted component supposed to have the correct inherited view encapsulation?  It doesn't work for me.  using 3.4.0

**Comment by arkon** [comment]
@kenisteward what are you expecting/seeing instead?

**Comment by kenisteward** [comment]
When the component is inserted in either case the attributes from the surrounding component for view encapsulation  are not added to the scg element.  There by breaking any styles you set with view encapsulation on .
