### ISSUE TITLE
Use with Ionic2

### ISSUE THREAD

**Issue by mikeTmw** [arkon/ng-inline-svg#26]
I am using ng-inline-svg with Ionic2, which specifies that all images go in the "src/assets/..." folder but uses webpack or something in the background to relocate those files to another location depending on the platform.

As such, Ionic2 specifies that in template files, assets should be referenced using, for example "assets/img/my-vector-image.svg". This causes problems with ng-inline-svg which is expecting (I guess) an absolute path to the location.

Is there any way that you are aware of to get ng-inline-svg to work nicely with Ionic2?

**Comment by arkon** [comment]
You just need to make sure the path you write is for the final relocated path. I don't think you need to do anything special otherwise?
