### ISSUE TITLE
Base href is determined incorrectly

### ISSUE THREAD

**Issue by Messier82** [arkon/ng-inline-svg#27]
Base href is determined incorrectly if application is running under some context, e.g.: http://localhost:8180/appname/%here's_actual_angular_app%
Directive is not 'seeing' "/appname/" context and trying to load from wrong location(not /appname/assets, but /assets)

**Comment by arkon** [comment]
The quick fix for you would be to pass in a URL like `"/appname/assets/my_img.svg"` for now. I'll work on adding a way to configure the base href though.

**Comment by arkon** [comment]
Added a way to do it in `master`, but I'll be adding some other things before publishing a new version.

**Comment by Messier82** [comment]
How long till update?

**Comment by Messier82** [comment]
And suggestion: can `<base href=""/>` property from index.html be used?

**Comment by arkon** [comment]
@Messier82 It is possible, but it might be easier to just let the user define it when adding the `InlineSVGModule` to their module. I also considered using `APP_BASE_HREF`, but it's possible that not everybody is using that.

**Comment by arkon** [comment]
@Messier82 Published v3.1.0 to NPM. Check out [the README](https://github.com/arkon/ng-inline-svg#usage) on how to manually define the base.

**Comment by Messier82** [comment]
The thing is, that i'm using Angular-CLI with --bh property. I want just to make this more dynamic. But anyways - many thanks for your update!
