### ISSUE TITLE
SystemJS error. Can't resolve all parameters for SVGCache

### ISSUE THREAD

**Issue by arusak** [arkon/ng-inline-svg#28]
I use angular 2.4.0 and ng-inline-svg 3.0.0. Modules a loaded via SystemJS. 
Trying to import InlineSVGModule in my SharedModule. Getting this:

`
(SystemJS) Can't resolve all parameters for SVGCache: (?, [object Object]).
`

Here's my system.config.js:
```
System.config({
  paths: {
    'libs:': './libs/'
  },
  map: {
    // ...
    'ng-inline-svg': 'libs:ng-inline-svg',
  },
  packages: {
    // ...
    'ng-inline-svg': {
      main: './lib/index.js',
      defaultExtension: 'js'
    }
  }
});
```

And shared.module.js:
```
// many imports go here
import {InlineSVGModule} from "ng-inline-svg";

@NgModule({
  imports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule,
    CoreModule,
    RouterModule,
    InlineSVGModule,
  ],
  exports: [
    BrowserModule,
    CommonModule,
    FormsModule,
    HttpModule,
    RouterModule,
    InlineSVGModule,
  ],
  declarations: [
    // ...
  ],
  providers: [ ],
})
export class SharedModule {}
```

All lib files are in place and I can see them downloaded in dev tools. 

Can you please help me?

**Comment by arkon** [comment]
ng-inline-svg v3.x requires Angular v4.x. I think the issue should be fixed if you update Angular.

**Comment by arusak** [comment]
Yep, the update fixes it. Thanks dude!
