### ISSUE TITLE
Can I overwrite style?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [arkon/ng-inline-svg#31]
I've a hamburger icon.
```
<svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
	 width="64px" height="64px" viewBox="0 0 64 64" enable-background="new 0 0 64 64" xml:space="preserve">
<line fill="none" stroke="#ffffff" stroke-width="2" stroke-miterlimit="10" x1="12" y1="21" x2="52" y2="21"/>
<line fill="none"   stroke="#ffffff" stroke-width="2" stroke-miterlimit="10" x1="12" y1="33" x2="52" y2="33"/>
<line fill="none"  stroke="#ffffff"  stroke-width="2" stroke-miterlimit="10" x1="12" y1="45" x2="52" y2="45"/>
</svg>

```
But by default it already has some color. I'm using few thousands  of icons. 
Can I overload it in css file? Cause right now it's not working as it is. And *!important* property doesn't help either.

**Comment by AlexanderKozhevin** [comment]
And it's not only about the colors. Same problem with the size.

**Comment by arkon** [comment]
Assuming you have something like the following (where `hamburger.svg` is the SVG you mentioned):

```html
<div class="my-svg" [inlineSVG]="'hamburger.svg'"></div>
```

You can style it by doing:

```css
.my-svg line {
  stroke: red !important;
}
```

Unfortunately, that means you need to be awfully specific with exactly what elements of the SVG you want to target, along with which attributes. Generally, you'd need to actually have better SVGs.

**Comment by AlexanderKozhevin** [comment]
I did that, and it doesn't feel like it's working at all. Ok, will dig deeper. 
Maybe there is some nasty stuff going on because of SCSS
```
.divclass > line{
    opacity: 0;
    stroke: blue!important;
  }
```

**Comment by arkon** [comment]
The `line` isn't a direct descendant of `.divclass`. It would probably be `.divclass > svg > line`.
