### ISSUE TITLE
Issue with unit testing inserted svg with karma runner

### ISSUE THREAD

**Issue by Mourdraug** [arkon/ng-inline-svg#35]
it('Should create new svg element', async(()=>{
        fixture.detectChanges();
        fixture.whenStable().then(()=>{
             //console.log(de.nativeElement.querySelector('#mapWrapper').innerHTML);
            expect(de.nativeElement.querySelector('svg')).toBeTruthy();
        });
    }));
I'd expect this to work, however commented out log prints empty string, and query cant find any svg element. Preview loads svg correctly. Am I missing something here?

**Comment by arkon** [comment]
I'm not sure if it's really done by the time `whenStable()` is resolved. You might need some extra `tick()` or `detectChanges()` calls or something, but I haven't used Angular's testing stuff before.
