### ISSUE TITLE
Configure baseUrl after compilation (outside of module.forRoot())

### ISSUE THREAD

**Issue by RodyKirwan1** [arkon/ng-inline-svg#36]
Hi, I'm having issues resolving a dynamic baseUrl within the forRoot() function during AOT.
I need to add a locale suffix to the baseHref depending on the environment. Currently I get this value from the DOM but this is not available for AOT compilation - is there a way to globally configure baseUrl after compilation?

**Comment by arkon** [comment]
You can do something like this now (v3.3.0) :

```ts
import { SVGCacheService } from 'ng-inline-svg';

class Whatever {
  constructor(service: SVGCacheService) {
    service.setBaseUrl({ baseUrl: 'https://google.ca/' });
  }
}
```

**Comment by RodyKirwan1** [comment]
Thanks @arkon. Will try it out :)
