### ISSUE TITLE
Using it with Ionic

### ISSUE THREAD

**Issue by giovannipds** [arkon/ng-inline-svg#37]
Hello. When I tried to use this package with Ionic, a simple path change produced different results. You can check it [here](https://stackoverflow.com/questions/40960428/ionic-svg-does-not-appear).

When using the code below, it has worked on the browser but hasn't worked when deployed to the device (android):

    <div class="my-icon" aria-label="My icon" [inlineSVG]="'/img/image.svg'"></div>

Changing to this (just a dot in the beginning of the path), has made it work both on the browser and on the device:

    <div class="my-icon" aria-label="My icon" [inlineSVG]="'./img/image.svg'"></div>

I think it worth to be mentioned on the readme, something like "**if you're using this package with Ionic, please be sure to specify the path like this**" + code.

Agree?

**Comment by arkon** [comment]
Just curious: does it work if you just remove the leading slash?

**Comment by giovannipds** [comment]
@arkon I'm gonna check it as soon as possible and inform you. Thanks for the interaction.

**Comment by giovannipds** [comment]
Hi @arkon. Sorry for my late response.

I tested it on another device (since I've finished the project I used this package and left the company where we built it). Although, I've tested it on another Android device (mobile this time, not tablet - but I don't think that's relevant, I guess).

**Yes. It works**, removing the leading slash works as well, as so:

    <div class="my-icon" aria-label="My icon" [inlineSVG]="'img/image.svg'"></div>

Don't know if that's a bug or what, but with the leading slash it continues not working, as pointed out before.

If there's anything else I could help you, please let me know. Cheers! o/

**Comment by arkon** [comment]
Thanks for checking it out. It's how I expect it to work, as it's just how absolute vs relative paths work.

**Comment by giovannipds** [comment]
Indeed, but as I've mentioned, `/img/...` works on browser, while developing, it just doesn't work when deployed. Doesn't worth to be mentioned?

**Comment by arkon** [comment]
It just depends on how you're delivering the assets (i.e. are they really available at the root or not). If this issue does arise, I'll just point them here. :)

**Comment by giovannipds** [comment]
k, np. ;) thanks.

**Comment by TeodorKolev** [comment]
This did not work in Android and iOS

**Comment by giovannipds** [comment]
@TeodorKolev it has worked to me, on Android, as pointed out. Are you sure you're trying to use it as we've suggested?

**Comment by TeodorKolev** [comment]
yes I am sure

**Comment by giovannipds** [comment]
@TeodorKolev at the time I've tested and we've wrote here, it was working. Ping @arkon, maybe it was something related to what he has recently changed.

**Comment by arkon** [comment]
Nothing should have changed regrading this. Not sure why it wouldn't work.

**Comment by MuhAssar** [comment]
@giovannipds try using android_asset/www at your root url, check my comment here:
https://github.com/arkon/ng-inline-svg/issues/58#issuecomment-364705186
