### ISSUE TITLE
Include OnChange Event

### ISSUE THREAD

**Issue by 3oax** [arkon/ng-inline-svg#4]
It is possible to include a "watch" method? Would be nice, if the url of the [inlineSVG] changes, the new src is inserted in the element.

edit: "workaround" at the moment:

import {
  Directive,
  ElementRef,
  EventEmitter,
  Input,
  OnInit,
  Output,
  OnChanges // <- this is new
} from '@angular/core';

[....]

ngOnChanges(){
  this.ngOnInit();
}

**Comment by arkon** [comment]
Published 0.3.1 to NPM with this!
