### ISSUE TITLE
Cannot find module '@angular/common/http'

### ISSUE THREAD

**Issue by di3orlive** [arkon/ng-inline-svg#42]
<details>
<summary>Error: Cannot find module '@angular/common/http'</summary>

```[13:36:04]  typescript: /node_modules/ng-inline-svg/lib/svg-cache.service.d.ts, line: 1
Cannot find module '@angular/common/http'.
L1:  import { HttpClient } from '@angular/common/http';
L2:  import { Observable } from 'rxjs/Observable';
```
</details>

```"ng-inline-svg": "^3.2.1" = working good```
```"ng-inline-svg": "^4.0.0" = err```

**Comment by arkon** [comment]
ng-inline-svg 4.x requires Angular >= 4.3.x.

I also realized I forgot to change the peer dependency on `@angular/http` to `@angular/common`, so I've fixed that in 4.0.1.
