### ISSUE TITLE
Still seeing error with @angular/common/http

### ISSUE THREAD

**Issue by jahagirdar** [arkon/ng-inline-svg#43]
I am still seeing related error in 4.0.1 of ng-inline-svg with angular 4.3.6
In the chrome console I see
Evaluating http://192.168.1.5:5000/ui/node_modules/@angular/common/bundles/common.umd.js/**http**

and in http://192.168.1.5:5000/ui/node_modules/ng-inline-svg/lib/svg-cache.service.js
var http_1 = require("@angular/common/http");

**Comment by arkon** [comment]
You could try Angular 4.4.0-RC.0 since that apparently fixed some bundling issue for the http subpackage. You can also just try nuking your `node_modules` and reinstalling everything again, since it should be fine.

**Comment by jahagirdar** [comment]
The solution at https://github.com/mgechev/angular-seed/issues/2046 worked.

Thanks for the quick response.
