### ISSUE TITLE
Importing HttpClientModule  overwrites existing HTTP_INTERCEPTORS

### ISSUE THREAD

**Issue by csomazoli** [arkon/ng-inline-svg#47]
### Repro

import `InlineSVGModule` in a lazy loaded module (I'm not sure it affects only lazy loaded ones), when `HTTP_INTERCEPTORS` are provided, and `HttpClientModule` is imported at a higher level (for example, in the root app module).

### Issue
`InlineSVGModule` imports `HttpClientModule`. Doing so overwrites existing `HTTP_INTERCEPTORS`.
According to angular docs, `HttpClientModule` should be imported only in the root module of the application.

I know your module relies on `HttpClientModule`, but instead of importing it yourself, you should leave it to the users to import it, so this way `HTTP_INTERCEPTORS` won't be overwritten.

**Comment by arkon** [comment]
Changed in v5.0.0.

**Comment by csomazoli** [comment]
Wow, thanks for the quick response!
