### ISSUE TITLE
Fetching svg from assets seems to fail when running on mobile

### ISSUE THREAD

**Issue by cuginoAle** [arkon/ng-inline-svg#52]
Hi there, thanks for this nice plugin.

I have some files in my src/assets/svg-icons folder
I use the plugin like this:
`<div class="svg-icon-wrapper" [inlineSVG]=svg></div>`
where svg resolves to: "assets/svg-icons/white-logo.svg"

If I run the ionic app in a browser everything works great but when I build the cordova app and run it on a real device (tested on android only) it fails.

Using Chrome inspector I see the following error: 
**GET file:///assets/svg-icons/white-logo.svg net::ERR_FILE_NOT_FOUND**
 
As a temporary work around I added the following:
    if (this.platform.is('cordova') && this.platform.is('android')) {
      this.url = '/android_asset/www/' + this.url;
    }

Is this the expected behaviour or should this be something the plugin should take care of?

thanks
Alessio

**Comment by arkon** [comment]
The plugin doesn't do anything special for Cordova, so it's just resolving the base to `file:///` automatically in that environment.

You could probably set the base like so:

```js
InlineSVGModule.forRoot({ baseUrl: '/android_asset/www/' })
```

**Comment by cuginoAle** [comment]
Thanks for clarifying this.
