### ISSUE TITLE
Dynamic image path - [inlineSVG]="'{{ imagePath }}'" 

### ISSUE THREAD

**Issue by rrubio** [arkon/ng-inline-svg#54]
Hi Guys,

I have a select box where a number of options are presented to the user for viewing. However, the following doesn't seem to work:

in 'image.ts':
`this.imagePath = selected.value; // 'images/my_image.svg'`

under template:
`<div class="demo-svg1" aria-label="My icon 1" [inlineSVG]="'{{imagePath}}'"></div>`

Any ideas are much appreciated :-)

**Comment by arkon** [comment]
Try just doing `[inlineSVG]="imagePath"`.

**Comment by rrubio** [comment]
Magic! thank you @arkon
