### ISSUE TITLE
innerhtml and UNSAFE_VAR_ASSIGNMENT

### ISSUE THREAD

**Issue by bufke** [arkon/ng-inline-svg#55]
Hello - the Mozilla package [web-ext](https://github.com/mozilla/web-ext/) is flagging the use of setting [innerHtml](https://github.com/arkon/ng-inline-svg/blob/933e5d8aaeaae2137bdca1d69d60fd117370fa3b/src/svg-cache.service.ts#L86) in this project as UNSAFE_VAR_ASSIGNMENT. Is there any alternative that could be used? 

Of note - angular based web extensions will not be accepted at all to the mozilla web ext store due to many reasons. But it would be nice to work on removing reasons they would reject a web ext.

**Comment by arkon** [comment]
This feels like a pretty valid usecase for using `innerHtml` though. Otherwise I'd need to do something like recursively recreate all the nodes and set the attributes, unless you know of a better way?
