### ISSUE TITLE
baseURL does not prepend image request when using symbol file with id references

### ISSUE THREAD

**Issue by jfarago** [arkon/ng-inline-svg#57]
in app.module
`InlineSVGModule.forRoot({ baseUrl: '/app/assets/icons/'})`

this doesnt work, the request doesnt have the prepended baseURL of /app/assets/icons/
`<div class="icon" [inlineSVG]="'symbol-defs.svg#sync_alarm'"></div>`

but if i remove the #sync_alarm it prepends.

My work around is to first load the symbols file and with display:none in the root component. Then its cached so i can reference it like so after.

`<div class="icon" [inlineSVG]="'#sync_alarm'"></div>`

Please let me know if im using this wrong, i saw in the documentation that there is support for symbol files but i didnt not see an example.

**Comment by arkon** [comment]
This is indeed a bug. I'll try to fix it within a day.

**Comment by jfarago** [comment]
Thank you very much for your quick reply. Great directive btw, saved me a lot of headaches.

**Comment by arkon** [comment]
Fixed in v5.1.4.
