### ISSUE TITLE
how to use string interpolation with InlineSVG

### ISSUE THREAD

**Issue by MuhAssar** [arkon/ng-inline-svg#59]
I want to load 500+ svg image so I use *ngFor to loop over them, but unfortunately hadn't success with doing so using interpolation
```
 <div *ngFor='let icon of icons'>
        <div  [inlineSVG]="'/img/{{icon}}.svg'"></div>
</div>
```

it raises error in "'/img/{{icon}}.svg'"

**Comment by arkon** [comment]
What's the error?

**Comment by MuhAssar** [comment]
sure I should have wrote the exact error message pardon me. But I didn't have access to my development pc so I wrote the issue with out the technical details out of the memory.

I researched it a little further and found that it is not ng-inline-svg specific issue, but rather it is something related to how angular treat the property binding:
https://stackoverflow.com/questions/42456459/got-interpolation-where-expression-was-expected

thanks for your work
