### ISSUE TITLE
Styling problems

### ISSUE THREAD

**Issue by kasienna** [arkon/ng-inline-svg#60]
SVGs within directive seem to be style encapsulated. I wonder how to apply my own component styles on svg loaded by directive.

This whole angular approach on partial including seems to be way too complicated

**Comment by kasienna** [comment]
I figured it out you need to add
`  encapsulation: ViewEncapsulation.None,
`
to the component definition. Perhaps it's worth to add this to docs

**Comment by arkon** [comment]
> This whole angular approach on partial including seems to be way too complicated

Yeah, that about sums up my thoughts on Angular. /shrug
