### ISSUE TITLE
SVG inserted twice when prepend is true

### ISSUE THREAD

**Issue by codedonkey** [arkon/ng-inline-svg#62]
Like the title says, using the prepend attribute causes the inline svg element to be inserted twice

`<div [inlineSVG]="imageUrl"  prepend="true"></div>`

Produces...

```
<div prepend="true" ng-reflect-inline-s-v-g="..." ng-reflect-prepend="true">
    <svg>...</svg>
    <svg>...</svg>
</div>
```

(using version 6.0.0)

**Comment by arkon** [comment]
Try doing `[prepend]="true"`?
