### ISSUE TITLE
IE11 svg with symbol

### ISSUE THREAD

**Issue by ibagaric** [arkon/ng-inline-svg#64]
How to display IE11 svg with symbol, as I  see in your it demo it does not work also:
<div [inlineSVG]="'img/symbol.svg#fish'"></div>

**Comment by arkon** [comment]
Seems like IE doesn't support using symbols via external references. I'll add a workaround at some point.

**Comment by arkon** [comment]
95c7a2f6096eb529971ad69dd8d4a5f736a81d2b
