### ISSUE TITLE
Using [attr.*] and other angular stuff in svg

### ISSUE THREAD

**Issue by tagazok** [arkon/ng-inline-svg#65]
Hi,
Here is the svg I am trying to insert : 
```xml
<svg xmlns="http://www.w3.org/2000/svg" width="300px" height="100px" viewBox="0 0 300 100">
    <svg:rect x="0" y="0" fill="none" width="300" height="100" [attr.stroke]="strokeColor" stroke-width="4" />
</svg>
```
This works perfectly when I directly write the svg in my html. However, it does not when I import it with ng-inline-svg. Nothing is displayed (but no error in the console either)

Any advice? :)

**Comment by arkon** [comment]
This library wasn't really meant for that since that would involve dynamic component injection which is a huge pain (at least it used to be, but I doubt it's gotten any better). Sorry. :(
