### ISSUE TITLE
SVG not appearing and no error message

### ISSUE THREAD

**Issue by zachrickards** [arkon/ng-inline-svg#66]
I haven't changed my baseUrl, I've tried changing all the relative paths and still nothing? I can reach the file at the appropriate location, for example "http:/localhost:4200/assets/svgs/temp.svg"

**Comment by zachrickards** [comment]
`<div style="fill: #ecf3f9; height: 6.5rem;" [inlineSVG]="'chevron_rt.svg'"></div>`

`InlineSVGModule.forRoot({ baseUrl: '/src/assets/svgs/' })`

**Comment by arkon** [comment]
Check your network tab and make sure it's actually requesting with the right URL.

**Comment by zachrickards** [comment]
It was requesting the right url. Error handling is poor and this shouldn't be closed. There is no way to trace what is happening

**Comment by arkon** [comment]
Why does the baseUrl include "src" if that's not actually part of the URL to the asset?

**Comment by arkon** [comment]
Is there anything in the actual DOM node?

**Comment by Maryna-Yelakova** [comment]
I have the same issue. There is just div element "div _ngcontent-c1="" ng-reflect-inline-s-v-g="/src/assets/images/svg/apple.s">div  I've tried changing path and baseUrl:
InlineSVGModule.forRoot({ baseUrl: '/src/assets/images/svg/'}),
 but it still does not work

**Comment by arkon** [comment]
Is there anything actually in the div but just not visible? Can you see a successful request to get the SVG file in the network tab of devtools?

**Comment by Maryna-Yelakova** [comment]
Request URL: https://rdev.wodcat.com/frontend/src/assets/images/svg/apple.svg
Request Method: GET
Status Code: 200 OK
 _ngcontent-c1="" ng-reflect-inline-s-v-g="apple.svg" - in the div 
but svg still not visible

**Comment by arkon** [comment]
If it's there inside the div, then there's likely something wrong with how the div is sized, or the SVG itself.

**Comment by Maryna-Yelakova** [comment]
I can change the size of my div but it shows up as an empty block with my width and height. Should I change path inside  [inlineSVG]? 
[inlineSVG]="'apple.svg'"

**Comment by arkon** [comment]
It's impossible for me to tell. If you can see that the SVG was injected into the DOM properly but it's still not possible, then that means this directive is functioning as expected, but you might need to tweak your SVG or div somehow.

**Comment by arquadrado** [comment]
I have exactly the same problem described above. I have the svg being loaded sucessfully in the network tab but then it is not added to the dom.

This is my component:
```
<div
  class="icon"
  [ngStyle]="{ width: width, height: height }"
  [inlineSVG]="imagePath"
  [setSVGAttributes]="{ style: 'position: absolute; top: 0; left: 0;' }"
></div>
```

and in the dom I just have the empty div

`<div _ngcontent-gmp-c5="" class="icon" ng-reflect-ng-style="[object Object]" ng-reflect-inline-s-v-g="assets/img/svg/menu.svg" ng-reflect-set-s-v-g-attributes="[object Object]" style="width: 32px; height: 32px;"></div>`

Did anyone managed to figure out what is happening here?

**Comment by danshif** [comment]
remove filter="url(#a)" from path in svg, for me its work! and show the svg icon

**Comment by gothaf** [comment]
This was really frustrating... I solved it by indicating the relative path to the image.
so from this: 
````
[inlineSVG]="/src/assets/img/image.svg"
````
I did this
````
[inlineSVG]="../../../../../assets/img/image.svg"
````
