### ISSUE TITLE
[Suggestion] Add the ability to change the preserveAspectRatio attribute

### ISSUE THREAD

**Issue by Jahrenski** [arkon/ng-inline-svg#67]
it would be helpful in some scenarios to be able to control the preserveAspectRatio to do things like: 
preserveAspectRatio="none"

It could be used as follow: 
`<div [inlineSVG]="'arrow.svg'" [preserveAspectRatio]="none"></div>`

**Comment by arkon** [comment]
I think a better idea would be having a lifecycle hook so you can manipulate the SVG prior to its insertion. I'd rather not have something this specific.

**Comment by arkon** [comment]
Added `[onSVGLoaded]` in v6.2.0, which you can use to manipulate the SVG element prior to it being inserted.

(Note that it doesn't work with symbols currently)
