### ISSUE TITLE
Possible solution for styles overwriting themselves?

### ISSUE THREAD

**Issue by gethinoakes** [arkon/ng-inline-svg#68]
If you use multiple SVG icons on the same page that have been exported from applications such as Adobe XD/Illustrator, their styles end up conflicting with each other.

One way around this is to go into each SVG's code and add a prefix to each style.
I was wondering if that could be done with this library? Some property such as `prefixClass` perhaps?

I'll try and have a look at your code when I have more time, but do you think this would be viable as the creator?

**Comment by arkon** [comment]
> do you think this would be viable

Yes, but it would be more so along the lines of [a lifecycle hook that I suggested in another issue](https://github.com/arkon/ng-inline-svg/issues/67#issuecomment-382448574). I'll try to get around to adding that soon.

**Comment by gethinoakes** [comment]
Great, I did see that and thought it could also work for this. Thanks for the quick response.

**Comment by arkon** [comment]
Added `[onSVGLoaded]` in v6.2.0, which you can use to manipulate the SVG element prior to it being inserted.

(Note that it doesn't work with symbols currently)
