### ISSUE TITLE
angular6 & rxjs 6 compatibility

### ISSUE THREAD

**Issue by fxuniverse** [arkon/ng-inline-svg#69]
![image](https://user-images.githubusercontent.com/5694399/39223703-8a40cc52-4811-11e8-85e3-d8477f2a3e02.png)

![image](https://user-images.githubusercontent.com/5694399/39223569-d21081d6-4810-11e8-9ac6-d2334b0ca587.png)

any chance to update import paths to new structure ? 

thanks in advance

**Comment by arkon** [comment]
I accept PRs, but I only target the stable version.
