### ISSUE TITLE
Fallback image option

### ISSUE THREAD

**Issue by arkon** [arkon/ng-inline-svg#7]

**Comment by danibuiza** [comment]
can you explain a bit this issue?

**Comment by arkon** [comment]
@danibuize Basically, there should be some way to specify a regular image as the fallback in case the SVG fails to load or the browser somehow doesn't support it. Of course, the user could just put a regular `<IMG>` tag inside, which would be displayed if it's never replaced, but I'd rather the browser not have to load that image if it's going to end up being replaced by an SVG anyway.

**Comment by LiorGonda** [comment]
Alternatively:
There is current a function onSVGInserted for success.
Having a onSVGInsertedFail function could be used to load an image.

This would be easy. In the directive, create a 2nd output for onSVGInsertedFail, and in the getSVG catch error, call the emit

**Comment by arkon** [comment]
@LiorGonda I've added an `onSVGFailed` output event in v1.4.0, but I'd like to tackle this issue later on as well.

**Comment by arkon** [comment]
Added in ed70d962a1a25b2506b1305702ff7761935711ee
