### ISSUE TITLE
Metadata version mismatch

### ISSUE THREAD

**Issue by wautersj** [arkon/ng-inline-svg#73]
Hey, i'm getting the following on ng serve:
What can I do to resolve this?

`ERROR in Error: Metadata version mismatch for module /Users/.../node_modules/ng-inline-svg/lib/index.d.ts, found version 4, expected 3, resolving symbol AppModule in /Users/.../src/app/app.module.ts, resolving symbol AppModule in /Users/.../src/app/app.module.ts`

**Comment by arkon** [comment]
Make sure whatever version of Angular and this library you're using are compatible. v7 of this lib requires Angular 6.

**Comment by wautersj** [comment]
Never had that before. I conform it works in version 6! Thanks!
