### ISSUE TITLE
Feature request: svg reload

### ISSUE THREAD

**Issue by zygimantas** [arkon/ng-inline-svg#74]
There is no way to re-run code in onSVGLoaded handler. The only option is to change the URL - prepend a random query parameter, like .svg?201805170012 In such case, a new request is made to the server.

Can we have a way to "repaint" the SVG file, without asking for a new file?
My use case is: I change the colors inside the SVG file depending on the application's state.

**Comment by zygimantas** [comment]
please ignore for few hours, I still have an idea

**Comment by zygimantas** [comment]
this is solvable by keeping the reference to the svg element in component state

**Comment by BennyAfriat** [comment]
> this is solvable by keeping the reference to the svg element in component state

Can you please explain more about your solution? i'm facing the same problem right now
