### ISSUE TITLE
Missing .metadata.json for for angular2 AOT compiler

### ISSUE THREAD

**Issue by tadchristiansenli** [arkon/ng-inline-svg#8]
I was upgrading to Ionic 2 RC0 and angular 2.0.1 and got the following error:

ngc error: Error: Unexpected value 'InlineSVGModule' imported by the module 'AppModule'

It occurs because Ionic 2 RC0 uses Ahead of Time (AoT) compiling and ng2-inline-svg does not have the .metadata.json file needed to use angular AoT.

**Comment by tadchristiansenli** [comment]
See explanation here: https://github.com/angular/angular/issues/11262

**Comment by arkon** [comment]
@tadchristiansenli Could you try v1.2.0?

**Comment by tadchristiansenli** [comment]
I just tried it and it appears to be working. I was just about to checkout your code and send you a pull request but you beat me to it. THANKS! I will let you know if I notice any issues once I can test this more thoroughly. Until then I will close this.
