### ISSUE TITLE
removeSVGAttributes doesn't remove XMLNS attribute tag

### ISSUE THREAD

**Issue by cgilbe27** [arkon/ng-inline-svg#88]
[removeSVGAttributes]="['xmlns']"
Attempting to use inline svg's and as such we don't need the xmlns tag (also its causes a problem upstream with Angular Universal \ Platform-server that was only fixed on Angular 6, we are on Angular 5)
Why does this not remove the problem child?

**Comment by arkon** [comment]
I believe I only implemented it to look at the nodes within the SVG element and not the parent node itself. Will fix.

**Comment by arkon** [comment]
Fixed in v8.0.2.
