### ISSUE TITLE
onSVGFailed not thrown on 404

### ISSUE THREAD

**Issue by Xample** [arkon/ng-inline-svg#89]
```html
<div class="my-icon" aria-label="My icon"
     [inlineSVG]="'http://anyUrl#symbolName'"
     (onSVGFailed)="error($event)"
></div>
```
```ts
    public error(element: SVGElement): void {
        alert('error'); // never called
    }
```

Let's consider I have a server with a 404 page at http://anyUrl#symbolName. It seems that the directive is taking the contant as valid and will load the svg with the 404 page's content instead of considering the 40X code as a failure.

I was expecting to get an error if:
- there is no file at the given url (error 404)
- (possibly) if the svg file is found but there is no symbol with `symbolName` found in the svg file

Is this the expected behaviour? if yes then is there any way to manually check the input and throw an error if the content is not valid?
I do think about the `onSVGLoaded` hook. Could I make it fail if I return `null`?

**Comment by arkon** [comment]
95c7a2f6096eb529971ad69dd8d4a5f736a81d2b
