### ISSUE TITLE
Component style doesn't get applied

### ISSUE THREAD

**Issue by MateEke** [arkon/ng-inline-svg#9]
If I use [inlineSVG] inside an angular2 component, the component's css doesn't get applied on the included svg element because the emulated encapsulation.

![capture](https://cloud.githubusercontent.com/assets/11072174/19680360/b020fa0c-9aa5-11e6-8a54-8dccc6bf6466.PNG)
![capture2](https://cloud.githubusercontent.com/assets/11072174/19680361/b0273ca0-9aa5-11e6-8be3-08148bc1a2b6.PNG)

**Comment by MateEke** [comment]
"/deep/ svg" solved the problem

**Comment by arkon** [comment]
Alrighty then 👍
