### ISSUE TITLE
ERROR Error: StaticInjectorError(AppModule)[InlineSVGDirective -> InlineSVGService]

### ISSUE THREAD

**Issue by ameetdhage** [arkon/ng-inline-svg#91]
Getting below error - 

ERROR Error: StaticInjectorError(AppModule)[InlineSVGDirective -> InlineSVGService]: 
  StaticInjectorError(Platform: core)[InlineSVGDirective -> InlineSVGService]: 
    NullInjectorError: No provider for InlineSVGService!
    at NullInjector.push../node_modules/@angular/core/fesm5/core.js.NullInjector.get (core.js:1062)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveToken (core.js:1300)
    at tryResolveToken (core.js:1244)
    at StaticInjector.push../node_modules/@angular/core/fesm5/core.js.StaticInjector.get (core.js:1141)
    at resolveNgModuleDep (core.js:8369)
    at NgModuleRef_.push../node_modules/@angular/core/fesm5/core.js.NgModuleRef_.get (core.js:9057)

![ng-inline-svg-error](https://user-images.githubusercontent.com/27812434/46796095-62f0ab80-cd69-11e8-8f08-ac7cb37d53f4.PNG)

My environment details - 

```
Angular CLI: 6.2.3
Node: 8.11.2
OS: win32 x64
Angular:
...
Package                      Version
------------------------------------------------------
@angular-devkit/architect    0.8.3
@angular-devkit/core         0.8.3
@angular-devkit/schematics   0.8.3
@schematics/angular          0.8.3
@schematics/update           0.8.3
rxjs                         6.2.2
typescript                   2.9.2
```

**Comment by arkon** [comment]
How did you add the module in your app?

**Comment by ameetdhage** [comment]
**Added module as shown in below code :** 
```
import { InlineSVGModule } from 'ng-inline-svg';

@NgModule({
    declarations: [],
    imports: [
        InlineSVGModule,
    ],
    exports: []
})
export class TestModule {}
```
**And used inlineSVG directive as follows-** 
```
@Component({
    selector: 'inline-svg-input',
    template: `
        <div>
            <mat-form-field [ngClass]="{'invalid-ssn': isInvalid}">
                <span class="icon" [inlineSVG]="'/assets/components/icons/eye-icon.svg'"
                      (click)="toggleView()">
                </span>
                <input 
                       matInput type="text"
                       [placeholder]="placeholder"
                       aria-required="true">
            </mat-form-field>
        </div>`,
})
export class TestComponent {

}

```

**Comment by ameetdhage** [comment]
@arkon 
FYI - 
Above code works well in Angular4.x.x
but fails in Angular 6.x.x

**Comment by arkon** [comment]
Try `InlineSVGModule.forRoot()`.

**Comment by ameetdhage** [comment]
@arkon 
Thank you very much it worked :)
