### ISSUE TITLE
Bundle size with ng-inline-svg

### ISSUE THREAD

**Issue by moniuch** [arkon/ng-inline-svg#92]
This module (functionally) works just great. Solves most of my project's SVG needs. The only problem - but huge enough to make itself almost unusable - is bundle size.

On a fresh `ng new myapp` application, with `ng-inline-svg` installed and `[inlineSVG]` applied to just one div, the bundle size after `ng build --prod --aot --build-optimizer` jumps from 170kb to 400+kb.

Is there anything you can do about it?

**Comment by arkon** [comment]
I don't have much knowledge about AOT optimizations (I stopped actively using Angular before AOT was really a thing), so I'd definitely be grateful for any pointers here.

**Comment by juliusstoerrle** [comment]
Just checked in my app with webpack-bundle-analyzer and for ng-inline-svg/lib it lists less than 3kb gziped.
In my code I'm only importing InlineSVGModule.

My app is not a fresh new application. maybe @moniuch you can use webpack-bundle-analyzer and check what takes the space in you build?

**Comment by ghost** [comment]
I agree with @juliusstoerrle it is very very small, when importing only the InlineSVGModule.

![image](https://user-images.githubusercontent.com/21689109/48473286-6fe53c80-e7f8-11e8-86ab-63a1d504a987.png)

**Comment by arkon** [comment]
Very interesting, thanks for the insight folks. @moniuch Have you been able to deep dive into your bundle size?

**Comment by intellix** [comment]
One improvement here would be using the new ng6 `@Injectable({ providedIn: 'root' })` so those services can be tree shaken if unused.

Then you can also deprecate/remove forRoot on the module too
