### ISSUE TITLE
rxjs as peerDependency

### ISSUE THREAD

**Issue by carmanchris31** [arkon/ng-inline-svg#93]
This package is great but I lost some valuable time troubleshooting SVGs not appearing in some circumstances. I eventually found this was occurring when they were loaded from cache and then to the 'of' function not being defined and finally to the rxjs version mismatch (5 vs 6).

We can save time for people like me (e.g. [here](https://github.com/arkon/ng-inline-svg/issues/79) and [here](https://github.com/arkon/ng-inline-svg/issues/77)) by declaring rxjs 6 as a `peerDependency`. That way a warning will be surfaced when installing/building if the version is not met.

**Comment by arkon** [comment]
Sorry, that's definitely a miss on my part! Added in v8.2.0.
